config/routes.rb
Rails.application.routes.draw do

  root 'pets#search'

  post 'populator/update', to: 'pet_populator#update', as: 'populate'
  post 'populator/reconcile', to: 'pet_populator#reconcile', as: 'reconcile'
  get 'pets/without-images', to: 'pet_populator#pets_without_images'
  get 'pets/external-ids', to: 'pet_populator#all_external_ids'
  post 'pet/:id/reconcile-image', to: 'pet_populator#reconcile_image'

  get 'search', to: 'pets#search', as: 'search'
  get 'results', to: 'pets#results', as: 'results'
  get 'pet/:id', to: 'pets#show', as: 'show'

  post 'subscribe', to: 'subscription#subscribe', as: 'subscribe'
  match 'confirm', to: 'subscription#confirm', as: 'confirm', via: [ :get, :post ]
  match 'unsubscribe', to: 'subscription#unsubscribe', as: 'unsubscribe', via: [ :get, :post ]

  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == Figaro.env.http_username && password == Figaro.env.http_password
  end
  mount Sidekiq::Web => '/sidekiq'

end

app/models/pet.rb
class Pet < ActiveRecord::Base
  include TimeScopable

  DEFAULT_IMG = "https://#{Figaro.env.s3_bucket}.s3.amazonaws.com/_default/pet-avatar.png"

  belongs_to :shelter

  scope :active, -> { where(active: true) }
  scope :imageless, -> { where(image: DEFAULT_IMG) }
  scope :type, ->(species) { where species: species }
  scope :maybe, ->(prop, value) { where(prop => value) unless value.nil? }
  scope :found_since, ->(date) { where("found_on > ?", date.midnight) unless date.nil? }
  scope :for_subscription, ->(subscription) { type(subscription.species).maybe(:gender, subscription.gender).found_since(subscription.found_since) }

  def self.from_hash(hash)
  	unless hash[:shelter_name].blank?
	  	shelter = Shelter.find_or_create_by(name: hash.delete(:shelter_name))  
	  	hash.merge! shelter: shelter
	  end

  	Pet.new(hash)
  end

  def mark_inactive!
    self.active = false
  end

  def active?
    active
  end

  def has_image?
    image != DEFAULT_IMG
  end

  def found_days_ago
    (Date.today - found_on.to_date).to_i unless found_on.nil?
  end

  def self.time_scopable_moment
    :found_on
  end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  def search
    @subscription = Subscription.new
  end

  def results
    @subscription = Subscription.new(subscription_params)
    @pets = Pet.active
      .for_subscription(@subscription)
      .reverse_chrono.order(:id)
      .page(params[:page]).per_page(20)
  end

  def show
    @back_url = request.referrer if request.referrer.present? && request.referrer.include?('results')
    @pet = Pet.find(params[:id])
  end

  private

  def subscription_params
    params.require(:subscription).permit(:email, :phone, :species, :found_since, :gender)
  end

end

app/views/pets/results.html.erb
<div class= "container">
	<div class= "subscription-form">
		<h2 class="call-to-action centered">Get Alerts for this Search</h2>
		<p class= "centered">
			Receive alerts by email or text message when a new pet matching this search is posted.
		</p>

		<%= form_for @subscription, url: subscribe_url, html: { method: 'post' } do |f| %>

		<div class='subscription-readonly-input'>
			<%= f.label 'species', 'Type:' %>
			<%= f.text_field 'species', class: 'form-control', readonly: true, placeholder: 'view all' %>
		</div>
		<div class='subscription-readonly-input'>
			<%= f.label 'gender', 'Gender:' %>
			<%= f.text_field 'gender', class: 'form-control', readonly: true, placeholder: 'view all' %>
		</div>
		<div class='subscription-readonly-input'>
			<%= f.label 'found', 'Found:' %>
			<%# subscription doesn't need this value as it only applies to future posts%>
			<%= f.text_field 'found_since', class: 'form-control', readonly: true, disabled: true, placeholder: 'view all' %>
		</div>

		<div class='subscription-input'>
			<%= f.label 'Sign up for email alerts' %>
			<%= f.email_field 'email', class: 'form-control', placeholder: 'you@example.com'  %>
		</div>
		<div class='subscription-input'>
			<%= f.label 'phone', 'Sign up for text message alerts (US only)' %>
			<%= f.phone_field 'phone', class: 'form-control', placeholder: '555-555-5555' %>
		</div>

		<%= f.submit "Submit", class: "submit-button" %>

		<p class= "centered">Cancel an alert any time by <%= link_to 'clicking here', unsubscribe_url %>.</p>
		<% end %>
	</div>
</div>


<div class= "second-form-background">
	<div class= "container">
		<div class="search-results-wrapper">
			<h2 class="call-to-action centered">Search Results</h2>

			<%= will_paginate @pets %>
			<table class="results-table">
				<% @pets.each do |pet| %>
				<tr class= "result-each">
					<td class= "result-image">
						<%= link_to show_path(pet) do %>
						<%= image_tag pet.image, class: 'pet-image' %>
						<% end %>
					</td>
					<td>
						<h5>
							<%= link_to show_path(pet), class: 'btn-link' do %>
							<%= "#{pet.color} #{pet.gender} #{pet.breed}".titleize %>
							<% end %>
						</h5>
						<% unless pet.found_on.nil? %>
						<p>Found <%= pluralize(pet.found_days_ago, 'day') %> ago (<%= pet.found_on.strftime("%b %-d %y") %>)</p>
						<% end %>
					</td>
				</tr>
				<% end %>
			</table>
			<%= will_paginate @pets %>

		</div>
	</div>
</div>

app/views/pets/search.html.erb
 <h2 class="main-title-caption"><div class="call-to-action-circle">1</div>Search Austin Animal Shelters for your pet</h2>

<%= form_for @subscription, url: { action: 'results' }, html: { method: 'get', id: 'temp_new_subscription' } do |f| %>
<div class= "container">
  <div class="wide-layout centered">
    <div class="row">

      <div class="col-xs-4">
        <div class='pet-icon dog-icon' data-species='dog'></div>
      </div>

      <div class="col-xs-4">
        <div class='pet-icon cat-icon' data-species='cat'></div>
      </div>

      <div class="col-xs-4">
        <div class='pet-icon other-icon' data-species='other'></div>
      </div>
      
    </div>
  </div>
</div>

<div class= "search-form">
  <div class= "container">

      <div class="collapse" id="hidden-form">
        <%= f.hidden_field 'species' %>
          <div class="call-to-action-circle">2</div>
          <%= f.label :found_since, '(Optional) Select Date and Gender' %>
        <div class='has-feedback'>
          <%= f.text_field :found_since, class: 'form-control ', placeholder: 'Date Lost' %>
          <i class="glyphicon glyphicon-calendar form-control-feedback"></i>
        </div>

          <div class="btn-group male-female-search" data-toggle="buttons">
            <label class="btn btn-default">
              <input type="radio" name="subscription[gender]" value="male"> Male
            </label>
            <label class="btn btn-default">
              <input type="radio" name="subscription[gender]" value="female"> Female
            </label>
          </div>

        <div class="actions">
          <%= f.submit "Search", disabled: true, class: "search-button" %>
        </div>

      </div>
  </div>
</div>

<% end %>

app/views/pets/show.html.erb
<div class="container">
  <div class = "wide-layout">
    <div class="centered">
      <div class="show-layout-box">
        <h3 class="pet-current-location">Currently located at: <br> 
          <a href="<%= @pet.shelter.map_link %>"><span class=" call-to-action glyphicon glyphicon-map-marker"></span><%= @pet.shelter %> (map)</a>
        </h3>
        <p class= "pet-id-number">Contact the animal shelter directly for further information on this pet and reference pet identifier '<%= @pet.pet_id %>'.</p>

        <div class="show-layout-copy">
          <h4><%= "#{@pet.gender} #{@pet.species}".titleize %></h4>
          <p>Found: <%= @pet.found_on.strftime("%B %d, %Y") %></p>
          <p>Breed guess: <%= @pet.breed %></p>
          <p>Color: <%= @pet.color %></p>
        </div>

        <img src="<%= @pet.image %>" class= "responsive-pet-icon"/>

        <% if @back_url.present? %>
        <%= link_to 'Return to Results', @back_url, class: 'return-button' %>
        <% end %>

      </div>
    </div>
  </div>          
</div>